Controllers/CongNhanController.cs
using Ky2_2019_2020.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace Ky2_2019_2020.Controllers
{
    public class CongNhanController : Controller {
        public IActionResult ListByTrieuChungForm() {
            return View();
        }

        [HttpPost]
        public IActionResult ListByTrieuChung(int soTc) {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            return View(context.sqlListByTrieuChungCongNhan(soTc));
        }

        public IActionResult ListByDiemCachLyForm() {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            return View(context.sqlListDiemCachLy());
        }

        [HttpPost]
        public IActionResult ListByDiemCachLy(string maDiemCachLy) {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            return View(context.sqlListByDiemCachLyCongNhan(maDiemCachLy));
        }

        public IActionResult Details(string maCongNhan) {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            return View(context.sqlFindCongNhanByMaCN(maCongNhan));
        }

        public string Delete(string maCongNhan) {
            int count;
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            count = context.sqlDeleteCongNhanByMaCN(maCongNhan);

            return (1 == count) ? "Delete successfully!" : "Something wrong...";
        }
    }
}

Controllers/DiemCachLyController.cs
using Ky2_2019_2020.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ky2_2019_2020.Controllers
{
    public class DiemCachLyController : Controller {
        public IActionResult ThemDiemCachLy() {
            return View();
        }

        [HttpPost]
        public string Create(DiemCachLyModel newDiemCachLy) {
            int count;
            DataContext context = HttpContext.RequestServices.GetService(typeof(Ky2_2019_2020.Models.DataContext)) as DataContext;

            count = context.sqlInsertDiemCachLy(newDiemCachLy);

            return (1 == count) ? "Insert successfully!" : "Something wrong...";
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ky2_2019_2020</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ky2_2019_2020</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DiemCachLy" asp-action="ThemDiemCachLy">Câu 1. Thêm điểm cách ly</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CongNhan" asp-action="ListByTrieuChungForm">Câu 2. Liệt kê theo số triệu chứng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CongNhan" asp-action="ListByDiemCachLyForm">Câu 3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Ky2_2019_2020 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>